[package]
name = "tree-sitter-ql"
description = "QL grammar for tree-sitter"
version = "0.23.0"
authors = ["Sam Lanning <sam@samlanning.com>"]
license = "MIT"
keywords = ["incremental", "parsing", "tree-sitter", "ql"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-ql"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.0"

[build-dependencies]
cc = "1.1.15"

[dev-dependencies]
tree-sitter = "0.23"
